# .github/workflows/tag-on-main.yml
name: Tag on main

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Bump version and tag
        run: |
          npm ci
          node scripts/bump-version.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json
          git commit -m "bump version"
          git push
          version=$(node -p "require('./package.json').version")
          git tag v$version
          git push origin v$version
